package com.example.domain

import androidx.compose.ui.graphics.Color
import kotlin.math.cos
import kotlin.math.sin

enum class DayPhase(
  val displayName: String,
  val iconEmoji: String,
  val isDark: Boolean,
  val description: String
) {
  MADRUGADA("Madrugada Fria", "🌌", true, "Frio congelante e escuridão densa. Feras noturnas caçam."),
  ALVORADA("Alvorada Dourada", "🌅", false, "O orvalho brilha e os primeiros raios de sol surgem no horizonte."),
  MANHA("Manhã Silvestre", "☀️", false, "Ar fresco e límpido. Cervos e pássaros pastam ativamente."),
  MEIO_DIA("Meio-Dia Solar", "🌞", false, "Luz máxima e clareza perfeita para explorar os cantos do mapa."),
  ENTARDECER("Pôr do Sol Dourado", "🌇", false, "Sombras se alongam e a temperatura começa a cair."),
  CREPUSCULO("Crepúsculo Místico", "🌆", true, "Céu púrpuro. Vaga-lumes despertam e animais procuram abrigo."),
  NOITE("Noite Selvagem", "🌙", true, "Escuridão perigosa. Feras espreitam na mata e temem o fogo.")
}

object DayNightCycleManager {

  fun getDayPhase(timeMinutes: Int): DayPhase {
    val m = (timeMinutes % 1440 + 1440) % 1440
    return when (m) {
      in 0 until 300 -> DayPhase.MADRUGADA     // 00:00 - 05:00
      in 300 until 420 -> DayPhase.ALVORADA    // 05:00 - 07:00
      in 420 until 720 -> DayPhase.MANHA       // 07:00 - 12:00
      in 720 until 960 -> DayPhase.MEIO_DIA    // 12:00 - 16:00
      in 960 until 1110 -> DayPhase.ENTARDECER // 16:00 - 18:30
      in 1110 until 1260 -> DayPhase.CREPUSCULO// 18:30 - 21:00
      else -> DayPhase.NOITE                   // 21:00 - 24:00
    }
  }

  /**
   * Continuous smooth ambient darkness multiplier from 0.0f (pure daylight noon) to 0.88f (pitch black midnight).
   */
  fun getAmbientDarkness(timeMinutes: Int): Float {
    val m = (timeMinutes % 1440 + 1440) % 1440

    return when {
      // Midnight / Madrugada (00:00 - 04:30)
      m in 0 until 270 -> 0.88f

      // Dawn: transition from 0.88 down to 0.0 (04:30 - 07:00, 150 min)
      m in 270 until 420 -> {
        val frac = (m - 270) / 150f
        0.88f * (1f - frac)
      }

      // Daylight: Morning & Noon (07:00 - 16:30)
      m in 420 until 990 -> 0.0f

      // Golden Hour / Sunset: transition from 0.0 up to 0.50 (16:30 - 18:30, 120 min)
      m in 990 until 1110 -> {
        val frac = (m - 990) / 120f
        0.50f * frac
      }

      // Twilight / Dusk: transition from 0.50 up to 0.88 (18:30 - 21:00, 150 min)
      m in 1110 until 1260 -> {
        val frac = (m - 1110) / 150f
        0.50f + (0.38f * frac)
      }

      // Deep Night (21:00 - 24:00)
      else -> 0.88f
    }
  }

  /**
   * Ambient atmospheric color tint overlay for mood and chromatic adaptation.
   */
  fun getAtmosphereColor(timeMinutes: Int): Color {
    val m = (timeMinutes % 1440 + 1440) % 1440

    return when {
      m in 0 until 270 -> Color(0xFF030712) // Deep Midnight Black/Indigo
      m in 270 until 360 -> Color(0xFF1A1A3A) // Pre-dawn Indigo
      m in 360 until 420 -> Color(0xFFD48166) // Soft Morning Rose / Gold
      m in 420 until 720 -> Color(0xFFFFFAED) // Warm Daylight
      m in 720 until 990 -> Color(0xFFFFFFFF) // Bright Noon Sun
      m in 990 until 1110 -> Color(0xFFFF9E80) // Sunset Warm Coral
      m in 1110 until 1260 -> Color(0xFF281C3E) // Twilight Purple
      else -> Color(0xFF070B18) // Night Indigo
    }
  }

  /**
   * Sun angle across the 360-degree sky dome (0 = horizon at 06:00, 90 = zenith at 12:00).
   */
  fun getCelestialAngle(timeMinutes: Int): Float {
    val m = (timeMinutes % 1440 + 1440) % 1440
    return ((m - 360).toFloat() / 1440f) * 360f
  }

  /**
   * Dynamic player vision radius:
   * During daylight: unlimited view.
   * At night: contracts to 90px if unlit, or expands to 220px if holding a torch.
   */
  fun getPlayerVisionRadius(timeMinutes: Int, hasTorch: Boolean): Float {
    val darkness = getAmbientDarkness(timeMinutes)
    if (darkness <= 0.05f) return 1000f // broad daylight

    val minRadius = if (hasTorch) 220f else 95f
    val maxRadius = 500f
    return maxRadius - (darkness * (maxRadius - minRadius))
  }

  /**
   * Ambient temperature offset generated by the day/night cycle.
   * Warmest at 14:00 (+2.5°C), Coldest at 04:00 (-6.0°C).
   */
  fun getCycleTemperatureOffset(timeMinutes: Int): Float {
    val m = (timeMinutes % 1440 + 1440) % 1440
    // Peaks at 14:00 (840 min), minimum at 02:00 (120 min)
    val rad = ((m - 840).toFloat() / 1440f) * 2f * Math.PI.toFloat()
    return cos(rad) * 4.2f
  }
}
